# File: .github/workflows/frontend-docker.yml
name: CI/CD Pipeline Next.js + Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js for Next.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      # Step 3: Install dependencies
      - name: Install frontend dependencies (Next.js)
        run: npm install

      # Step 4: Build frontend (Next.js)
      - name: Build frontend (Next.js)
        run: npm run build
        env:
          NODE_ENV: production
          API_URL: http://backend:8000/api
          NEXT_PUBLIC_API_URL: http://backend:8000/api

      # Step 5: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Step 6: Build and push Docker image
      - name: Build and Push Docker Image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Ensure this exists in your repo
          push: true
          tags: |
            achrefmaarfi0/planit_frontend_docker:latest
            achrefmaarfi0/planit_frontend_docker:${{ github.sha }}

  deploy:
    # This job depends on the build-and-push job finishing successfully
    needs: build-and-push
    runs-on: ubuntu-latest

    # IMPORTANT: Only run this step on a push to the master branch, NOT on pull requests.
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Navigate to the directory containing your production docker-compose file
            cd /planit

            # Pull the newest images from Docker Hub that were just pushed
            docker compose -f docker-compose.yml pull

            # Stop and restart all services with the new images
            # The .env file in this directory provides the environment variables
            docker compose -f docker-compose.yml up -d --remove-orphans

            # Clean up old, unused Docker images to save space
            docker image prune -af
